[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -machine virt -kernel"
rustflags = [
    "-Clink-arg=-Tkernel/linker.ld",
    "-Cforce-frame-pointers=yes",
]
